### ISSUE TITLE
Errors when accessing UDRs in a different Azure subscription

### ISSUE THREAD

**Issue by redditchpaul** [mspnp/ha-nva#45] opened 2017-11-30 10:41 UTC
We seem to have an issue when accessing resources in the different subscription to the Azure subscription defined for the subscriptionId under settings in the JSON file. When clientMonitor1 is created, the log file shows successfully getting the publicIpAddresses and NVA networkInterfaces, but errors when attempting to get the UDR. Any advice or guidance would be very much appreciated.

Here's the an extract from the log showing successful gets and errors:
2017-11-30 09:33:18,211 DEBUG [Curator-LeaderSelector-0:AzureClient$AzureClientImpl@144] - Getting resource: /subscriptions/<subscription1>/resourceGroups/NE-SS-FG-RG/providers/Microsoft.Network/networkInterfaces/NVA1nic3
2017-11-30 09:33:18,241 DEBUG [Curator-LeaderSelector-0:AzureClient$AzureClientImpl@151] - Got resource: /subscriptions/<subscription1>/resourceGroups/NE-SS-FG-RG/providers/Microsoft.Network/networkInterfaces/NVA1nic3
2017-11-30 09:33:18,392 DEBUG [Curator-LeaderSelector-0:AzureClient$AzureClientImpl@144] - Getting resource: /subscriptions/<subscription1>/resourceGroups/NE-SS-FG-RG/providers/Microsoft.Network/networkInterfaces/NVA2nic3
2017-11-30 09:33:18,444 DEBUG [Curator-LeaderSelector-0:AzureClient$AzureClientImpl@151] - Got resource: /subscriptions/<subscription1>/resourceGroups/NE-SS-FG-RG/providers/Microsoft.Network/networkInterfaces/NVA2nic3
2017-11-30 09:33:18,989 DEBUG [pool-5-thread-1:NvaMonitor$MonitorCallable@91] - Starting monitor task
2017-11-30 09:33:18,990 DEBUG [pool-5-thread-1:AzureClient$AzureClientImpl@144] - Getting resource: /subscriptions/<subscription1>/resourceGroups/NE-SS-NET-RG/providers/Microsoft.Network/publicIPAddresses/PIP01
2017-11-30 09:33:19,017 DEBUG [pool-5-thread-1:AzureClient$AzureClientImpl@151] - Got resource: /subscriptions/<subscription1>/resourceGroups/NE-SS-NET-RG/providers/Microsoft.Network/publicIPAddresses/PIP01
2017-11-30 09:33:19,019 DEBUG [pool-5-thread-1:AzureClient$AzureClientImpl@144] - Getting resource: /subscriptions/<subscription2>/resourceGroups/NE-UAT-NET-RG/providers/Microsoft.Network/routeTables/NE-Uat-Udr
2017-11-30 09:33:19,094 ERROR [Curator-LeaderSelector-0:NvaLeaderSelectorListenerAdapter@73] - Error executing NvaMonitor
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.microsoft.azure.practices.nvadaemon.NvaLeaderSelectorListenerAdapter.takeLeadership(NvaLeaderSelectorListenerAdapter.java:61)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:534)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.microsoft.azure.management.network.implementation.RouteTablesImpl.wrapModel(RouteTablesImpl.java:74)
        at com.microsoft.azure.management.network.implementation.RouteTablesImpl.getByGroup(RouteTablesImpl.java:46)
        at com.microsoft.azure.management.network.implementation.RouteTablesImpl.getByGroup(RouteTablesImpl.java:18)
        at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:60)
        at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.getById(GroupableResourcesImpl.java:31)
        at com.microsoft.azure.practices.nvadaemon.AzureClient$AzureClientImpl.getById(AzureClient.java:146)
        at com.microsoft.azure.practices.nvadaemon.AzureClient$AzureClientImpl.getRouteTableById(AzureClient.java:126)
        at com.microsoft.azure.practices.nvadaemon.AzureProbeMonitor.lambda$getCurrentNvaIndex$2(AzureProbeMonitor.java:91)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.microsoft.azure.practices.nvadaemon.AzureProbeMonitor.getCurrentNvaIndex(AzureProbeMonitor.java:92)
        at com.microsoft.azure.practices.nvadaemon.AzureProbeMonitor.init(AzureProbeMonitor.java:282)
        at com.microsoft.azure.practices.nvadaemon.NvaMonitor$MonitorCallable.call(NvaMonitor.java:94)
        at com.microsoft.azure.practices.nvadaemon.NvaMonitor$MonitorCallable.call(NvaMonitor.java:72)
        ... 4 more
2017-11-30 09:33:19,094 INFO  [Curator-LeaderSelector-0:NvaMonitor@176] - Stopping NvaMonitor task
2017-11-30 09:33:19,095 DEBUG [Curator-LeaderSelector-0:NvaMonitor@180] - Signalling NvaMonitor condition
2017-11-30 09:33:19,095 DEBUG [Curator-LeaderSelector-0:NvaMonitor@182] - Signalled NvaMonitor condition

**Comment by luisgmsft** [comment] 2018-08-30 20:00
@redditchpaul, can you please provide some more details on you deployed architecture? I tried to reproduce the error but in the end, I couldn't understand how your deployment was set and what were you trying to achieve.

Please let me know so I can have a better look.

**Comment by jocontr** [comment] 2020-05-13 17:44
Closing this issue due to a "No repro"

**Closed by jocontr** 2020-05-13 17:44 UTC
